### ISSUE TITLE
Deadlock where Broker.mu is never released

### ISSUE THREAD

**Issue by DrTall** [optiopay/kafka#49]
Howdy,

@zorkian and I discovered an issue where the Broker goes braindead because some goroutine has hung forever while holding the lock. We saw many calls to `PartitionCount` blocked on the mutex for hours. Unfortunately we have not yet been able to conclusively reproduce this.

We suspect that the culprit might be`fetchMetadata` because it looks fishy that this function makes an rpc while holding the lock and it doesn't use the typical Go idiom of a timeout channel. It looks like we are trusting the TCP library to honor the timeout settings. But we don't know for sure.

Any thoughts?

Cheers

**Comment by zorkian** [comment]
To add a little bit more color -- the wedge is in such a way that it can't ever produce again. All attempts to produce end up blocked and no packets are ever sent. This helps us believe it's in the metadata processing somewhere.

Also, the initial incident was caused by one of our brokers going bad in such a way that the host disappeared from the network abruptly.

**Comment by husio** [comment]
I can have a look later, but without any clue what is going wrong or how to reproduce the problem it might be impossible to find the problem.

**Comment by DrTall** [comment]
Right, I understand. I thought we'd open the issue just for tracking and
hopefully somebody (including us) will stumble on more details later?

**Comment by keep94** [comment]
I've been running into this same problem myself. Best I can tell, it goes all the way down to the "kafka.connection" level. Each kafka.connection keeps a map of correlation IDs (request IDs) to channels that hold the response for the corresponding request. Sending a request to Kafka involves the following:

1. Getting the next Correlation ID (request ID)
2. Registering a channel with that correlation ID in the connection's map.
3. Sending the request tagged with the correlation ID
4. Blocking on the corresponding channel

A single goroutine is in charge of reading responses off the socket and dispatching them to the corresponding requester. It does this by doing the following in an infinite loop.

1. Read the next response.
2. Using the correlation ID in the response, look up the right channel in the connection's map
3. Push the response to that channel

If a requesting goroutine were to successfully send out a KAFKA request on the socket, and the request never makes it to KAFKA or KAFKA ignores the request, then the response handling goroutine I mentioned above would never read a response for that request off the socket. Consequently, the response goroutine would never push any response onto that requester's channel, and the requester would be blocked forever.

This happens quite often in my environment. 

Sometimes the very first Metadata request blocks in this manner so that my application blocks before it can even start up!

It would probably make sense to add a timeout when reading the response channel using a select block. That way, if reading from the channel times out, optiopay/KAFKA can report an error up to its client instead of blocking its client indefinitely.

**Comment by husio** [comment]
@keep94 Good spot. Here's very raw code change, just to figure out if changes are going the right direction: https://github.com/optiopay/kafka/commit/f16386858ad0f02d5089c5577ae8849525d0b5ec

It was not tested yet, but I cannot work on it this week.

**Comment by keep94** [comment]
Would it be worth making timeout configureable instead of hard coding to 1
minute?

**Comment by husio** [comment]
It probably does. The is no reason why I picked one minute and not any other value. As I said this commit still requires a lot of work and I cannot do this anytime soon. Sorry.
